[build-system]
requires = ["maturin>=11.0"]
build-backend = "maturin"

[project]
name = "spatialtis_core"
dependencies = [
    'scipy',
    'torch',
    'torch-geometric',
    'pytorch-lightning',
    'somoclu',
    'patsy'
]